### PR TITLE
Add ThriftyNovaSwerve to YAGSL

### PR DESCRIPTION
**Pull request by clrozeboom**
Now that Thrifty has released their library, I was able to complete the work I started on this. It still needs work as more updates are published, but it's a good start.

### CODE REVIEW

**Comment by thenetworkgrinch** [comment]
Could you resolve these conflicts when you get a chance?

**Comment by clrozeboom** [comment]
Yeah, I'll take a look at it. I haven't gotten a controller to work with yet, not sure when I might.

**Comment by clrozeboom** [comment]
I'm uncertain what the conflicts are, so many changes. I wonder if we should start over. Most of these are files that are new.

**Comment by thenetworkgrinch** [comment]
Have you hit the "sync fork" button on the repo yet?

**Comment by clrozeboom** [comment]
No, I'll see if that helps in a bit.

**Pull request closed without merging**
