### PR TITLE
maple-sim new version

### PR DESCRIPTION
**Pull request by catr1xLiu**
The code updates to the next version of maple-sim (v0.2.3).

There are no significant changes, only small API upgrades.

It's not a necessary upgrade, so no hurries.  Please review it whenever you like.

### CODE REVIEW

**Comment by thenetworkgrinch** [comment]
@catr1xLiu Is this complete?

**Comment by catr1xLiu** [comment]
still working on the documents for the new version, give me like a day or two.

**Comment by catr1xLiu** [comment]
In this commit, I've added this method `getMapleSimDrive()` to the `SwerveDrive` class.  This allows users can add intake simulation or launch gamepieces from the drivetrain.  Which fixes this:
image

And we can finally get rid of the two deprecated methods, since users can now obtain the reference to the simulated drivetrain.

**Comment by thenetworkgrinch** [comment]
Just needs that merge conflict resolved. If you don't get to it tonight I can do it tomorrow however it wouldn't be in this PR and i would just manually commit to the `dev` branch. Thank you for your development on MapleSim!

**Comment by catr1xLiu** [comment]
No problem, I've resolved the conflict. And you're welcome!

**Review by thenetworkgrinch — APPROVED** [review]

**Review by thenetworkgrinch — APPROVED** [review]
Awesome as usual! Thank you so much for this :)

**Pull request merged**
